blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/Callmeduobgne/luongthiOlympic/discussions
    about: HÃ£y há»i vÃ  tháº£o luáº­n vá» dá»± Ã¡n táº¡i Ä‘Ã¢y
  - name: ğŸ“š Documentation
    url: https://github.com/Callmeduobgne/luongthiOlympic/tree/main/docs
    about: Xem tÃ i liá»‡u dá»± Ã¡n


